version: 3
services:
  mysql:
    restart: always
    image: mysql:5.7.16
    container_name: mysql
    volumes:
      - /root/mysqldocker/mydir:/mydir
      - /root/myslqdocker/datadir:/datadir
      - /root/mysqldocker/conf/my.conf:/etc/my.conf
      - /root/mysqldocker/source:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=test
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
